development:
    adapter: postgresql
    encoding: unicode
    database: pmt
    pool: 5
    host: localhost
    username: root
    password: root

# test:
#   <<: *default
#   database: myapp_test

# production:
#   <<: *default
#   database: myapp_production
#   username: myapp
#   password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>